lib/phoenix_elixir_dokku_web/router.ex
defmodule PhoenixElixirDokkuWeb.Router do
  use PhoenixElixirDokkuWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhoenixElixirDokkuWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/runtime-error-conn", PageController, :runtime_error_conn
    get "/runtime-error-match", PageController, :runtime_error_match
    get "/config", ConfigController, :index
  end

end

lib/phoenix_elixir_dokku/application.ex
defmodule PhoenixElixirDokku.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      PhoenixElixirDokkuWeb.Endpoint,
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: PhoenixElixirDokku.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    PhoenixElixirDokkuWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/phoenix_elixir_dokku/repo.ex
defmodule PhoenixElixirDokku.Repo do
  # use Ecto.Repo,
  #   otp_app: :phoenix_elixir_dokku,
  #   adapter: Ecto.Adapters.Postgres
end

lib/phoenix_elixir_dokku_web/controllers/config_controller.ex
defmodule PhoenixElixirDokkuWeb.ConfigController do
  use PhoenixElixirDokkuWeb, :controller

  require Logger

  defimpl Jason.Encoder, for: [Tuple] do
    def encode(struct, opts) do
      Jason.Encode.list(Tuple.to_list(struct), opts)
    end
  end

  def index(conn, params) do
    data_form = %{}

    data_assign = [
      {:truncate, 8192},
      {:level, "info"},
      {:sync_threshold, 20},
      {:discard_threshold, 500},
      {:handle_otp_reports, true},
      {:handle_sasl_reports, false},
      {:discard_threshold_periodic_check, 30_000}
    ]

    data_form =
      data_assign
      |> Enum.reduce(
        data_form,
        fn {k, defv}, data_form ->
          kstr = Atom.to_string(k)
          defvstr = "#{defv}"
          cfg = Application.get_env(:logger, k, defvstr)
          defvstr = "#{cfg}"
          param = Map.get(params, kstr, defvstr)

          v =
            cond do
              is_number(defv) ->
                case Integer.parse(param) do
                  {v, _} -> v
                  _ -> defv
                end

              k == :level ->
                case param do
                  "debug" -> :debug
                  "info" -> :info
                  "warn" -> :warn
                  "error" -> :error
                  _ -> Application.get_env(:logger, :level, :info)
                end

              true ->
                case param do
                  "true" -> true
                  "false" -> false
                end
            end

          Application.put_env(:logger, k, v)
          Map.put(data_form, k, v)
        end
      )

    console_backend = Application.get_env(:logger, :console)

    console_backend_assign = [
      {:max_buffer, 32},
      {:handle_otp_reports, true},
      {:handle_sasl_reports, false},
      {:device, :user}
    ]

    {console_backend, data_form_all} =
      console_backend_assign
      |> Enum.reduce(
        {console_backend, data_form},
        fn {k, defv}, {console_backend, data_form} ->
          kstr = "console_#{Atom.to_string(k)}"
          defvstr = "#{defv}"
          cfg = Keyword.get(console_backend, k, defvstr)
          defvstr = "#{cfg}"
          param = Map.get(params, kstr, defvstr)

          v =
            cond do
              is_number(defv) ->
                case Integer.parse(param) do
                  {v, _} -> v
                  _ -> defv
                end

              k == :device ->

                case param do
                  "user" -> :user
                  "standard_error" -> :standard_error
                end

              true ->
                case param do
                  "true" -> true
                  "false" -> false
                end
            end

          {
            Keyword.put(console_backend, k, v),
            Map.put(data_form, String.to_atom(kstr), v)
          }
        end
      )

    Application.put_env(:logger, :console, console_backend)
    Logger.configure_backend(:console, console_backend)

    keys = [:console, :backends, :compile_time_application, :compile_time_purge_matching]

    inspection =
      keys
      |> Enum.map(fn k -> {k, Application.get_env(:logger, k)} end)
      |> Enum.into(%{})

    Logger.configure(
      data_form
      |> Map.to_list()
    )

    inspection = Map.put(inspection, :logger, data_form)

    data_form_all = Map.put(data_form_all, :inspection, Jason.encode!(inspection, pretty: true))

    Logger.debug("debug message")
    Logger.info("info message")
    Logger.warn("warn message")
    Logger.error("error message")

    render(conn, "index.html", data_form_all)
  end
end

lib/phoenix_elixir_dokku_web/controllers/fallback_controller.ex
defmodule PhoenixElixirDokkuWeb.FallbackController do
  @moduledoc """
  Translates controller action results into valid `Plug.Conn` responses.

  See `Phoenix.Controller.action_fallback/1` for more details.
  """
  use PhoenixElixirDokkuWeb, :controller

  def call(conn, {:error, :not_found}) do
    conn
    |> put_status(:not_found)
    |> put_view(PhoenixElixirDokkuWeb.ErrorView)
    |> render(:"404")
  end
end

lib/phoenix_elixir_dokku_web/controllers/page_controller.ex
defmodule PhoenixElixirDokkuWeb.PageController do
  use PhoenixElixirDokkuWeb, :controller
  require Logger

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def runtime_error_match(conn, params) do
    Logger.error("Custom error message before runtime_error params")
    IO.inspect(params, label: "runtime_error params")
    1 = params
  end

  def runtime_error_conn(conn, _params) do
    Logger.error("Custom error message before runtime_error conn")
    IO.puts("runtime_error conn")
    PhoenixElixirDokkuWeb.Router.Helpers.page_path()
    conn
  end
end

lib/phoenix_elixir_dokku_web/views/changeset_view.ex
defmodule PhoenixElixirDokkuWeb.ChangesetView do
  use PhoenixElixirDokkuWeb, :view

  @doc """
  Traverses and translates changeset errors.

  See `Ecto.Changeset.traverse_errors/2` and
  `PhoenixElixirDokkuWeb.ErrorHelpers.translate_error/1` for more details.
  """
  def translate_errors(changeset) do
    Ecto.Changeset.traverse_errors(changeset, &translate_error/1)
  end

  def render("error.json", %{changeset: changeset}) do
    # When encoded, the changeset returns its errors
    # as a JSON object. So we just pass it forward.
    %{errors: translate_errors(changeset)}
  end
end

lib/phoenix_elixir_dokku_web/views/config_view.ex
defmodule PhoenixElixirDokkuWeb.ConfigView do
  use PhoenixElixirDokkuWeb, :view
end

lib/phoenix_elixir_dokku_web/views/error_view.ex
defmodule PhoenixElixirDokkuWeb.ErrorView do
  use PhoenixElixirDokkuWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/phoenix_elixir_dokku_web/views/layout_view.ex
defmodule PhoenixElixirDokkuWeb.LayoutView do
  use PhoenixElixirDokkuWeb, :view
end

lib/phoenix_elixir_dokku_web/views/page_view.ex
defmodule PhoenixElixirDokkuWeb.PageView do
  use PhoenixElixirDokkuWeb, :view
end

lib/phoenix_elixir_dokku_web/templates/config/index.html.eex
<h2>Config</h2>

<div class="form-grid">
<%= form_for @conn, Routes.config_path(@conn, :index), [method: "get"], fn f -> %>
    <div class="section">
    <div class="label">Logger</div>
    <div class="group">
  <label>
    Truncate: <%= number_input f, :truncate, value: @truncate %>
  </label>
  <label>
    Sync threshold: <%= number_input f, :sync_threshold, value: @sync_threshold %>
  </label>
  <label>
    Discard threshold: <%= number_input f, :discard_threshold, value: @discard_threshold %>
  </label>
    <label>
    Level
   <%=  select(f, :level, ["debug": "debug", "info": "info", "warn": "warn", "error": "error"], value: @level) %>
    </label>
    <label>
    Handle OTP Reports
   <%=  select(f, :handle_otp_reports, ["true": "true", "false": "false"], value: @handle_otp_reports) %>
    </label>
    <label>
    Handle SASL Reports
   <%=  select(f, :handle_sasl_reports, ["true": "true", "false": "false"], value: @handle_sasl_reports) %>
    </label>
    <label>
    Discard Threshold Periodic Check
   <%=  number_input(f, :discard_threshold_periodic_check, value: @discard_threshold_periodic_check) %>
    </label>
    </div>
    </div>

    <div class="section">
    <div class="label">Logger Backends: Console</div>
    <div class="group">
    <label>
      Max Buffer: <%= number_input f, :console_max_buffer, value: @console_max_buffer %>
    </label>
    <label>
    Handle OTP Reports
   <%=  select(f, :console_handle_otp_reports, ["true": "true", "false": "false"], value: @console_handle_otp_reports) %>
    </label>
    <label>
    Handle SASL Reports
   <%=  select(f, :console_handle_sasl_reports, ["true": "true", "false": "false"], value: @console_handle_sasl_reports) %>
    </label>
    <label>
    Device
   <%=  select(f, :console_device, ["user": "user", "standard_error": "standard_error"], value: @console_device) %>
    </label>
    </div>
    </div>

    <div class="section">
<label>
  <%= submit "Update" %>
</label>
</div>

<% end %>

<pre><code><%= @inspection %></code></pre>

lib/phoenix_elixir_dokku_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>PhoenixElixirDokku</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation" style="display:flex; flex-direction:row">
          <ul>
            <li><a href="<%= Routes.page_path(@conn, :index) %>">@home</a></li>
          </ul>
          <ul>
            <li><a href="<%= Routes.config_path(@conn, :index) %>">/config</a></li>
          </ul>
          <ul>
            <li><a href="<%= Routes.page_path(@conn, :runtime_error_match) %>">/runtime-error-match</a></li>
          </ul>
          <ul>
            <li><a href="<%= Routes.page_path(@conn, :runtime_error_conn) %>">/runtime-error-conn</a></li>
          </ul>
        </nav>
      </section>
    </header>
    <main role="main" class="<%= Map.get(@conn.assigns, :style_layout, "container") %>">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <footer>
    <section>
      <nav role="navigation" style="display:flex; flex-direction:row">
      <ul>
      <li>
        <div>Mix Project version: <%= PhoenixElixirDokku.MixProject.project[:version] %></div>
      </li>
      <li>
        <div>Mix.env: <%= Mix.env() %></div>
      </li>
      </ul>
      </nav>
    </section>
    </footer>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/phoenix_elixir_dokku_web/templates/page/index.html.eex
<section class="phx-hero">
  <h2><%= gettext "Welcome to %{name}!", name: "PhoenixElixirDokku" %></h2>
</section>

<article style="text-align: center; padding: 5rem 0">
  <ul style="list-style:none">
   <li>Mix Project version: <%= PhoenixElixirDokku.MixProject.project[:version] %></li>
   <li>Mix.env: <%= Mix.env() %></li>
  </ul>
</article>

<article>
You can use the API endpoint directly:
<pre><code>curl -sS -q -X GET -H "Content-Type: application/json" <%= PhoenixElixirDokkuWeb.Endpoint.url() %>/api/users | jq
</code></pre>
</article>

<article>
ChangeLog:
<pre><code><%= PhoenixElixirDokku.MixProject.changelog() %></code></pre>
</article>

<article>
Versions:
<pre><code><%= PhoenixElixirDokku.MixProject.deps_lock() %></code></pre>
</article>